mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("add/", views.add_poll, name="add_poll")
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days = 1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from django.forms import HiddenInput
from .models import Question, Choice

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text']

ChoiceFormSet = forms.inlineformset_factory(
    Question,
    Choice,
    fields=['choice_text'],
    extra=3,
    can_delete=False,
    widgets={'DELETE': HiddenInput()},
)

polls/views.py
from django.http import HttpResponseRedirect
from django.views import generic
from django.shortcuts import get_object_or_404, render
from .models import Choice, Question
from django.urls import reverse
from django.utils import timezone
from django.shortcuts import render, redirect
from .forms import QuestionForm, ChoiceFormSet

# Create your views here.
class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte = timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


def add_poll(request):
    if request.method == 'POST':
        question_form = QuestionForm(request.POST)
        choice_formset = ChoiceFormSet(request.POST)

        if question_form.is_valid() and choice_formset.is_valid():
            question = question_form.save(commit=False)
            question.pub_date = timezone.now()
            question.save()
            choice_formset.instance = question
            choice_formset.save()
            return redirect('polls:index')
    else:
        question_form = QuestionForm()
        choice_formset = ChoiceFormSet()

    return render(request, 'polls/add_poll.html', {
        'question_form': question_form,
        'choice_formset': choice_formset,
    })

polls/templates/polls/add_poll.html
<!doctype html>
<nav class="navbar navbar-expand-sm bg-light">

  <div class="container-fluid">
    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'polls:index' %}">Polls List</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'polls:add_poll' %}">Create A New Poll</a>
      </li>
    </ul>
  </div>

</nav>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <style>
        body {
            background: url('/static/polls/images/background.png');
            background-size: cover;
            background-repeat: no-repeat;
        }
    </style>
</head>
<body>
    <div class="container d-flex justify-content-center align-items-center vh-100" style = "margin-bottom: 100px;">
        <div class="text-center">
            <h1>Add a New Question</h1>
            <form method="post" action="{% url 'polls:add_poll' %}">
                {% csrf_token %}
                    <div class = "input-group mb-3">
                        <span class="input-group-text">Question</span>
                        <input type="text" class="form-control" id="{{ question_form.question_text.id_for_label }}" name="{{ question_form.question_text.name }}">
                    </div>
                <h1>Add Some Choices</h1>
                {{ choice_formset.management_form }}
                {% for form in choice_formset %}
                    {{ form.as_p }}
                {% endfor %}
                <input type="submit" value="Submit" class = "btn btn-primary">
            </form>
            <ul class="list-unstyled">
            <li style = "margin-top: 10px;"><a href="{% url 'polls:index' %}" class="btn btn-success custom-button">Go back to Polls List</a></li>
            </ul>
        </div>
    </div>
</body>
</html>
<html class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body class="d-flex flex-column h-100">
    <footer class="footer mt-auto py-3 bg-dark">
      <div class="container text-center">
        <span class="text-light">Author: Aaron Ko</br>©2023 Copyright | All Rights Reserved.</span>
      </div>
    </footer>
  </body>
</html>

polls/templates/polls/detail.html
<!doctype html>
<nav class="navbar navbar-expand-sm bg-light">

  <div class="container-fluid">
    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'polls:index' %}">Polls List</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'polls:add_poll' %}">Create A New Poll</a>
      </li>
    </ul>
  </div>

</nav>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <style>
        body {
            background: url('/static/polls/images/background.png');
            background-size: cover;
            background-repeat: no-repeat;
        }
    </style>
</head>
<body>
    <div class="container d-flex justify-content-center align-items-center vh-100" style = "margin-bottom: 100px;">
        <div class="text-center">
            <h1>{{ question.question_text }}</h1>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
                {% for choice in question.choice_set.all %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                {% endfor %}
            <input type="submit" value="Vote">
            </form>
            <ul class="list-unstyled">
            <li style = "margin-top: 10px;"><a href="{% url 'polls:index' %}" class="btn btn-success custom-button">Go back to Polls List</a></li>
            </ul>
        </div>
    </div>
</body>
</html>
<html class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body class="d-flex flex-column h-100">
    <footer class="footer mt-auto py-3 bg-dark">
      <div class="container text-center">
        <span class="text-light">Author: Aaron Ko</br>©2023 Copyright | All Rights Reserved.</span>
      </div>
    </footer>
  </body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<style>
    .custom-button{
    width: 170px;
    height: 40px
    }
</style>
<nav class="navbar navbar-expand-sm bg-light">

  <div class="container-fluid">
    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'polls:index' %}">Polls List</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'polls:add_poll' %}">Create A New Poll</a>
      </li>
    </ul>
  </div>

</nav>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Polls</title>
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <style>
        body {
            background: url('/static/polls/images/background.png');
            background-size: cover;
            background-repeat: no-repeat;
        }
    </style>
</head>
<body>
    <img src = "/static/polls/images/question.png" class = "rounded" alt = "Question" width = "200" height = "200">
    <div class="container d-flex justify-content-center align-items-center vh-100" style = "margin-bottom: 100px;">
        <div class="text-center">
            <h1>Current Polls</h1>
            {% if latest_question_list %}
                <ul class="list-unstyled">
                {% for question in latest_question_list %}
                    <li style = "margin-bottom: 10px;"><a href="{% url 'polls:detail' question.id %}" class="btn btn-primary">{{ question.question_text }}</a></li>
                {% endfor %}
                </ul>
            {% else %}
                <p>No polls are available.</p>
            {% endif %}
            <h1>Click here to create a poll</h1>
            <a href="{% url 'polls:add_poll' %}" class="btn btn-success custom-button">Create a New Poll</a>
        </div>
    </div>
</body>
</html>
<html class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body class="d-flex flex-column h-100">
    <footer class="footer mt-auto py-3 bg-dark">
      <div class="container text-center">
        <span class="text-light">Author: Aaron Ko</br>©2023 Copyright | All Rights Reserved.</span>
      </div>
    </footer>
  </body>
</html>

polls/templates/polls/results.html
<!doctype html>
<nav class="navbar navbar-expand-sm bg-light">

  <div class="container-fluid">
    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'polls:index' %}">Polls List</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'polls:add_poll' %}">Create A New Poll</a>
      </li>
    </ul>
  </div>

</nav>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <style>
        body {
            background: url('/static/polls/images/background.png');
            background-size: cover;
            background-repeat: no-repeat;
        }
    </style>
</head>
<div class="container d-flex justify-content-center align-items-center vh-100" style = "margin-bottom: 100px;">
    <div class="text-center">
        <body>
            <h1>{{ question.question_text }}</h1>
            <ul class = "list-unstyled">
            {% for choice in question.choice_set.all %}
                <div class = "table-responsive-sm">
                    <table class = "table">
                        <thead>
                            <tr>
                                <th>{{ choice.choice_text }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th>{{ choice.votes }} vote{{ choice.votes|pluralize }}</th>
                            </tr>
                        </tbody>
                    </table>
                </div>
            {% endfor %}
            </ul>
            <ul class = "list-unstyled">
            <li style = "margin-bottom: 10px;"><a href="{% url 'polls:detail' question.id %}" class="btn btn-success custom-button">Vote again?</a><br></li>
            <a href="{% url 'polls:index' %}" class="btn btn-primary custom-button">Go back to Polls List</a>
            </ul>
        </body>
    </div>
</div>
</html>
<html class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body class="d-flex flex-column h-100">
    <footer class="footer mt-auto py-3 bg-dark">
      <div class="container text-center">
        <span class="text-light">Author: Aaron Ko</br>©2023 Copyright | All Rights Reserved.</span>
      </div>
    </footer>
  </body>
</html>